### ISSUE TITLE
More animations

### ISSUE THREAD

**Issue by ludamad** [serprex/openEtG#43]
It would be nice if cards animated systematically as they did things, e.g. as they transitioned from zone to zone, gained resources, etc. CSS animations and https://github.com/chenglou/react-motion got me far in my card game (heavy WIP)

More general note, right now I feel like I have to play the original Elements, grok it, then I can come back.

**Comment by serprex** [comment]
Forum thread started on animations: https://etg.dek.im/forum/index.php?topic=871

On the general note, [Discord](https://discordapp.com/invite/qAmfB8T) chat is quite active for guidance

**Comment by serprex** [comment]
So started looking into this, & it's pushing me in the direction that the engine needs to be moved towards a full blown ECS. So let's hijack this thread & define what I mean by that

Currently AI bottleneck is primarily cloning game state. With an immutable game state cloning becomes free. Except the other way of looking at it is that all mutations incur the cost of cloning, so by that I'm really talking about sharing state between clones, ie copy-on-write

A feature I'd like to implement is game replays, there's the wire protocol that could be encoded to base64, but I'd like to support rewinding when viewing a replay (without having to compute backwards by replaying from start). This would all be simpler with an immutable game object

The wrench in the gears is that whenever an instance is updated their references need to be updated. Unfortunately this ends up meaning changing everything because there's a lot of back references (creatures point at player, player points at game, game points at players, player points at creatures)

Currently instances types are determined by which zone they're in. Think more like MtG having a battlefield & a graveyard, as opposed to creatures / enchantments. This lines up literally with the game ui's field layout

We don't currently generate an integer id for instances. That'd be the first step. This id could then be used as a key by the UI in order to animate motions between zones. But React only respects keys for children ordering, not moving around the tree. So we'll want to flatten the UI tree to one big list of everything on the field

For now we could keep the existing game-object structure (just add ids) & then have zone/index/etc be passed to `ThingInst`

**Comment by serprex** [comment]
Immutable merged, so we're now using react-motion for moving instances around field
