### ISSUE TITLE
Suggestion: swap to Roboto

### ISSUE THREAD

**Issue by FluffyDiscord** [serprex/openEtG#51]
Current font is, well, not optimal. Swapping to some free option, such as Roboto, makes quite a difference and I don't think, it's that hard to do so.

![image](https://user-images.githubusercontent.com/10332247/97082991-b448fc00-160d-11eb-9fd8-88eba6f5d3f0.png)

![image](https://user-images.githubusercontent.com/10332247/97083000-bc08a080-160d-11eb-9cd4-2342129bfdc2.png)

**Comment by serprex** [comment]
We used to use a webfont, [Dosis](https://fonts.google.com/specimen/Dosis). Roboto seems a bit too wide, you can see Water Pendulum's m being clipped

I since switched to using the user's system sans serif font, which is generally recommended. But our case might call for something else with the intersection of tight spacing & pixel specific coordinates being used everywhere
